// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjneroqndhwrqyibxslo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqbmVyb3FuZGh3cnF5aWJ4c2xvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTkxMjcsImV4cCI6MjA2NTkzNTEyN30.hoZP6MZjt65ez8YoTwW_TRWVGf8XhuuCwvouqld-2QE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);